// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbkdf2.proto

package jo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Kdf_HashAlg int32

const (
	Kdf_SHA256   Kdf_HashAlg = 0
	Kdf_SHA512   Kdf_HashAlg = 1
	Kdf_SHA3_224 Kdf_HashAlg = 2
	Kdf_SHA3_256 Kdf_HashAlg = 3
	Kdf_SHA3_384 Kdf_HashAlg = 4
	Kdf_SHA3_512 Kdf_HashAlg = 5
)

var Kdf_HashAlg_name = map[int32]string{
	0: "SHA256",
	1: "SHA512",
	2: "SHA3_224",
	3: "SHA3_256",
	4: "SHA3_384",
	5: "SHA3_512",
}

var Kdf_HashAlg_value = map[string]int32{
	"SHA256":   0,
	"SHA512":   1,
	"SHA3_224": 2,
	"SHA3_256": 3,
	"SHA3_384": 4,
	"SHA3_512": 5,
}

func (x Kdf_HashAlg) String() string {
	return proto.EnumName(Kdf_HashAlg_name, int32(x))
}

func (Kdf_HashAlg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_86d88026b4f876a9, []int{0, 0}
}

type Kdf struct {
	Salt                 []byte      `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Key                  []byte      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	KeyLen               int64       `protobuf:"varint,3,opt,name=key_len,json=keyLen,proto3" json:"key_len,omitempty"`
	Iter                 int64       `protobuf:"varint,4,opt,name=iter,proto3" json:"iter,omitempty"`
	Alg                  Kdf_HashAlg `protobuf:"varint,5,opt,name=alg,proto3,enum=jo.Kdf_HashAlg" json:"alg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Kdf) Reset()         { *m = Kdf{} }
func (m *Kdf) String() string { return proto.CompactTextString(m) }
func (*Kdf) ProtoMessage()    {}
func (*Kdf) Descriptor() ([]byte, []int) {
	return fileDescriptor_86d88026b4f876a9, []int{0}
}

func (m *Kdf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kdf.Unmarshal(m, b)
}
func (m *Kdf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kdf.Marshal(b, m, deterministic)
}
func (m *Kdf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kdf.Merge(m, src)
}
func (m *Kdf) XXX_Size() int {
	return xxx_messageInfo_Kdf.Size(m)
}
func (m *Kdf) XXX_DiscardUnknown() {
	xxx_messageInfo_Kdf.DiscardUnknown(m)
}

var xxx_messageInfo_Kdf proto.InternalMessageInfo

func (m *Kdf) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *Kdf) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Kdf) GetKeyLen() int64 {
	if m != nil {
		return m.KeyLen
	}
	return 0
}

func (m *Kdf) GetIter() int64 {
	if m != nil {
		return m.Iter
	}
	return 0
}

func (m *Kdf) GetAlg() Kdf_HashAlg {
	if m != nil {
		return m.Alg
	}
	return Kdf_SHA256
}

func init() {
	proto.RegisterEnum("jo.Kdf_HashAlg", Kdf_HashAlg_name, Kdf_HashAlg_value)
	proto.RegisterType((*Kdf)(nil), "jo.kdf")
}

func init() { proto.RegisterFile("pbkdf2.proto", fileDescriptor_86d88026b4f876a9) }

var fileDescriptor_86d88026b4f876a9 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x6f, 0x83, 0x30,
	0x10, 0x46, 0x6b, 0x4c, 0x48, 0x75, 0x42, 0xad, 0x75, 0x4b, 0x3d, 0xd2, 0x4c, 0x4c, 0x96, 0x6a,
	0x42, 0xd4, 0x95, 0x8d, 0xa1, 0x13, 0x99, 0x3a, 0x45, 0x44, 0x18, 0x5a, 0x6c, 0x61, 0x04, 0x2c,
	0xfc, 0xd1, 0xfe, 0x9e, 0xca, 0x16, 0x22, 0xdb, 0x7b, 0xdf, 0xe9, 0x0d, 0x07, 0xf1, 0x78, 0xd7,
	0x4d, 0x2b, 0xc5, 0x38, 0xd9, 0xc5, 0x62, 0xd0, 0xdb, 0xd3, 0x1f, 0x01, 0xaa, 0x9b, 0x16, 0x11,
	0xc2, 0xb9, 0x36, 0x0b, 0x27, 0x09, 0x49, 0xe3, 0xca, 0x33, 0x32, 0xa0, 0x5a, 0xad, 0x3c, 0xf0,
	0x93, 0x43, 0x7c, 0x83, 0xa3, 0x56, 0xeb, 0xcd, 0xa8, 0x81, 0xd3, 0x84, 0xa4, 0xb4, 0x8a, 0xb4,
	0x5a, 0xbf, 0xd4, 0xe0, 0xf2, 0xdf, 0x45, 0x4d, 0x3c, 0xf4, 0xab, 0x67, 0x7c, 0x07, 0x5a, 0x9b,
	0x8e, 0x1f, 0x12, 0x92, 0xbe, 0xc8, 0x57, 0xd1, 0x5b, 0xa1, 0x9b, 0x56, 0x94, 0xf5, 0xfc, 0x53,
	0x98, 0xae, 0x72, 0xb7, 0xd3, 0x37, 0x1c, 0x37, 0x47, 0x80, 0xe8, 0x5a, 0x16, 0x32, 0xbf, 0xb0,
	0xa7, 0x8d, 0xf3, 0x0f, 0xc9, 0x08, 0xc6, 0xf0, 0x7c, 0x2d, 0x8b, 0xec, 0x26, 0xe5, 0x99, 0x05,
	0x0f, 0xcb, 0x2f, 0x8c, 0xee, 0x96, 0x7d, 0x9e, 0x59, 0xb8, 0x9b, 0xeb, 0x0e, 0xf7, 0xc8, 0xff,
	0x98, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xba, 0x67, 0x98, 0xa2, 0xf3, 0x00, 0x00, 0x00,
}
